<?php

namespace App\Modules\emergencia\requests;

use Illuminate\Foundation\Http\FormRequest;

class RegistroEmergenciaStoreRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    public function rules(): array
    {
        return [
            'orden' => ['nullable', 'string', 'max:50'],
            'hora' => ['nullable', 'string', 'max:20'],
            'numero_hc' => ['required', 'string', 'max:50'],
            'apellidos_nombres' => ['required', 'string', 'max:255'],
            'sexo' => ['nullable', 'string', 'max:20'],
            'tipo_cliente' => ['nullable', 'string', 'max:100'],
            'fecha' => ['required', 'date'],
            'cuenta' => ['nullable', 'string', 'max:100'],
            'medico_emergencia' => ['nullable', 'string', 'max:255'],
            'medico_especialista' => ['nullable', 'string', 'max:255'],
            'topico' => ['nullable', 'string', 'max:100'],
            'numero_cuenta' => ['nullable', 'string', 'max:100'],
            'estado' => ['nullable', 'string', 'max:20'],
            'tipo_emergencia_id' => ['nullable', 'integer', 'exists:tipo_emergencia,id'],
            'topico_id' => ['nullable', 'integer', 'exists:topicos,id'],
            'medico_emergencia_id' => ['nullable', 'integer', 'exists:medicos,id'],
            'diagnostico_ingreso' => ['nullable', 'string', 'max:500'],
            'soat_activo' => ['nullable', 'boolean'],
            'soat_tipo_documento_id' => ['nullable', 'integer', 'exists:tipo_documento,id'],
            'soat_numero_documento' => ['nullable', 'string', 'max:100'],
            'soat_titular_referencia' => ['nullable', 'string', 'max:255'],
            'soat_poliza' => ['nullable', 'string', 'max:100'],
            'soat_placa' => ['nullable', 'string', 'max:50'],
            'soat_siniestro' => ['nullable', 'string', 'max:255'],
            'soat_tipo_accidente' => ['nullable', 'string', 'max:255'],
            'soat_lugar_accidente' => ['nullable', 'string', 'max:255'],
            'soat_dni_conductor' => ['nullable', 'string', 'max:50'],
            'soat_apellido_paterno_conductor' => ['nullable', 'string', 'max:255'],
            'soat_apellido_materno_conductor' => ['nullable', 'string', 'max:255'],
            'soat_contacto_conductor' => ['nullable', 'string', 'max:100'],
            'soat_fecha_siniestro' => ['nullable', 'date'],
            'soat_hora_siniestro' => ['nullable', 'string', 'max:20'],
            'soat_datos_intervencion_autoridad' => ['nullable', 'string', 'max:500'],
            'soat_documento_atencion_id_1' => ['nullable', 'integer', 'exists:documento_atencion,id'],
            'soat_numero_documento_atencion_1' => ['nullable', 'string', 'max:100'],
            'soat_documento_atencion_id_2' => ['nullable', 'integer', 'exists:documento_atencion,id'],
            'soat_numero_documento_atencion_2' => ['nullable', 'string', 'max:100'],
        ];
    }

    public function messages(): array
    {
        return [
            'orden.string' => 'El orden del registro de emergencia debe ser texto.',
            'orden.max' => 'El orden del registro de emergencia no debe superar 50 caracteres.',
            'hora.string' => 'La hora del registro de emergencia debe tener un formato válido.',
            'hora.max' => 'La hora del registro de emergencia no debe superar 20 caracteres.',
            'numero_hc.required' => 'Selecciona un paciente antes de guardar el registro de emergencia.',
            'numero_hc.string' => 'El número de historia clínica debe ser texto.',
            'numero_hc.max' => 'El número de historia clínica no debe superar 50 caracteres.',
            'apellidos_nombres.required' => 'El paciente seleccionado no tiene nombres completos para registrar la emergencia.',
            'apellidos_nombres.string' => 'Los apellidos y nombres del paciente deben ser texto.',
            'apellidos_nombres.max' => 'Los apellidos y nombres del paciente no deben superar 255 caracteres.',
            'sexo.string' => 'El sexo del paciente debe ser texto.',
            'sexo.max' => 'El sexo del paciente no debe superar 20 caracteres.',
            'tipo_cliente.string' => 'El tipo de cliente debe ser texto.',
            'tipo_cliente.max' => 'El tipo de cliente no debe superar 100 caracteres.',
            'fecha.required' => 'La fecha del registro de emergencia es obligatoria.',
            'fecha.date' => 'La fecha del registro de emergencia debe ser una fecha válida.',
            'cuenta.string' => 'La cuenta de referencia debe ser texto.',
            'cuenta.max' => 'La cuenta de referencia no debe superar 100 caracteres.',
            'medico_emergencia.string' => 'El médico de emergencia debe ser texto.',
            'medico_emergencia.max' => 'El médico de emergencia no debe superar 255 caracteres.',
            'medico_especialista.string' => 'El médico especialista debe ser texto.',
            'medico_especialista.max' => 'El médico especialista no debe superar 255 caracteres.',
            'topico.string' => 'El tópico debe ser texto.',
            'topico.max' => 'El tópico no debe superar 100 caracteres.',
            'numero_cuenta.string' => 'El número de cuenta debe ser texto.',
            'numero_cuenta.max' => 'El número de cuenta no debe superar 100 caracteres.',
            'estado.string' => 'El estado del registro de emergencia debe ser texto.',
            'estado.max' => 'El estado del registro de emergencia no debe superar 20 caracteres.',
            'tipo_emergencia_id.integer' => 'Selecciona un tipo de emergencia válido.',
            'tipo_emergencia_id.exists' => 'El tipo de emergencia seleccionado no existe.',
            'topico_id.integer' => 'Selecciona un tópico válido.',
            'topico_id.exists' => 'El tópico seleccionado no existe.',
            'medico_emergencia_id.integer' => 'Selecciona un médico de emergencia válido.',
            'medico_emergencia_id.exists' => 'El médico de emergencia seleccionado no existe.',
            'diagnostico_ingreso.string' => 'El diagnóstico de ingreso debe ser texto.',
            'diagnostico_ingreso.max' => 'El diagnóstico de ingreso no debe superar 500 caracteres.',
            'soat_activo.boolean' => 'El indicador SOAT debe ser verdadero o falso.',
            'soat_tipo_documento_id.integer' => 'Selecciona un tipo de documento SOAT válido.',
            'soat_tipo_documento_id.exists' => 'El tipo de documento SOAT seleccionado no existe.',
            'soat_numero_documento.string' => 'El número de documento SOAT debe ser texto.',
            'soat_numero_documento.max' => 'El número de documento SOAT no debe superar 100 caracteres.',
            'soat_titular_referencia.string' => 'El titular o referencia SOAT debe ser texto.',
            'soat_titular_referencia.max' => 'El titular o referencia SOAT no debe superar 255 caracteres.',
            'soat_poliza.string' => 'La póliza SOAT debe ser texto.',
            'soat_poliza.max' => 'La póliza SOAT no debe superar 100 caracteres.',
            'soat_placa.string' => 'La placa SOAT debe ser texto.',
            'soat_placa.max' => 'La placa SOAT no debe superar 50 caracteres.',
            'soat_siniestro.string' => 'El siniestro SOAT debe ser texto.',
            'soat_siniestro.max' => 'El siniestro SOAT no debe superar 255 caracteres.',
            'soat_tipo_accidente.string' => 'El tipo de accidente SOAT debe ser texto.',
            'soat_tipo_accidente.max' => 'El tipo de accidente SOAT no debe superar 255 caracteres.',
            'soat_lugar_accidente.string' => 'El lugar del accidente SOAT debe ser texto.',
            'soat_lugar_accidente.max' => 'El lugar del accidente SOAT no debe superar 255 caracteres.',
            'soat_dni_conductor.string' => 'El DNI del conductor SOAT debe ser texto.',
            'soat_dni_conductor.max' => 'El DNI del conductor SOAT no debe superar 50 caracteres.',
            'soat_apellido_paterno_conductor.string' => 'El apellido paterno del conductor SOAT debe ser texto.',
            'soat_apellido_paterno_conductor.max' => 'El apellido paterno del conductor SOAT no debe superar 255 caracteres.',
            'soat_apellido_materno_conductor.string' => 'El apellido materno del conductor SOAT debe ser texto.',
            'soat_apellido_materno_conductor.max' => 'El apellido materno del conductor SOAT no debe superar 255 caracteres.',
            'soat_contacto_conductor.string' => 'El contacto del conductor SOAT debe ser texto.',
            'soat_contacto_conductor.max' => 'El contacto del conductor SOAT no debe superar 100 caracteres.',
            'soat_fecha_siniestro.date' => 'La fecha del siniestro SOAT debe ser una fecha válida.',
            'soat_hora_siniestro.string' => 'La hora del siniestro SOAT debe tener un formato válido.',
            'soat_hora_siniestro.max' => 'La hora del siniestro SOAT no debe superar 20 caracteres.',
            'soat_datos_intervencion_autoridad.string' => 'Los datos de intervención de autoridad SOAT deben ser texto.',
            'soat_datos_intervencion_autoridad.max' => 'Los datos de intervención de autoridad SOAT no deben superar 500 caracteres.',
            'soat_documento_atencion_id_1.integer' => 'Selecciona un primer documento de atención SOAT válido.',
            'soat_documento_atencion_id_1.exists' => 'El primer documento de atención SOAT seleccionado no existe.',
            'soat_numero_documento_atencion_1.string' => 'El primer número de documento de atención SOAT debe ser texto.',
            'soat_numero_documento_atencion_1.max' => 'El primer número de documento de atención SOAT no debe superar 100 caracteres.',
            'soat_documento_atencion_id_2.integer' => 'Selecciona un segundo documento de atención SOAT válido.',
            'soat_documento_atencion_id_2.exists' => 'El segundo documento de atención SOAT seleccionado no existe.',
            'soat_numero_documento_atencion_2.string' => 'El segundo número de documento de atención SOAT debe ser texto.',
            'soat_numero_documento_atencion_2.max' => 'El segundo número de documento de atención SOAT no debe superar 100 caracteres.',
        ];
    }
}
