<?php

return [
    'models' => [
        \App\Modules\admision\models\Especialidad::class => ['module' => 'ficheros', 'entity' => 'especialidad'],
        \App\Modules\admision\models\Consultorio::class => ['module' => 'ficheros', 'entity' => 'consultorio'],
        \App\Modules\admision\models\Medico::class => ['module' => 'ficheros', 'entity' => 'medico'],
        \App\Modules\admision\models\Turno::class => ['module' => 'ficheros', 'entity' => 'turno'],
        \App\Modules\admision\models\Cliente::class => ['module' => 'ficheros', 'entity' => 'cliente'],
        \App\Modules\admision\models\Paquete::class => ['module' => 'ficheros', 'entity' => 'paquete'],
        \App\Modules\admision\models\Cirugia::class => ['module' => 'ficheros', 'entity' => 'cirugia'],
        \App\Modules\admision\models\TipoIafa::class => ['module' => 'ficheros', 'entity' => 'tipo_iafa'],
        \App\Modules\admision\models\Iafa::class => ['module' => 'ficheros', 'entity' => 'iafa'],
        \App\Modules\admision\models\Contratante::class => ['module' => 'ficheros', 'entity' => 'contratante'],
        \App\Modules\admision\models\Tarifa::class => ['module' => 'ficheros', 'entity' => 'tarifa'],
        \App\Modules\admision\models\TipoCliente::class => ['module' => 'ficheros', 'entity' => 'tipo_cliente'],
        \App\Modules\admision\models\TarifaRecargoNoche::class => ['module' => 'ficheros', 'entity' => 'recargo_noche'],
        \App\Modules\admision\models\AreaJefatura::class => ['module' => 'ficheros', 'entity' => 'area_jefatura'],
        \App\Modules\admision\models\CajaTipoDocumento::class => ['module' => 'ficheros', 'entity' => 'caja_tipo_documento'],
        \App\Modules\admision\models\CajaNumeracionComprobante::class => ['module' => 'ficheros', 'entity' => 'caja_numeracion_comprobante'],
        \App\Modules\admision\models\CajaFormaPago::class => ['module' => 'ficheros', 'entity' => 'caja_forma_pago'],
        \App\Modules\admision\models\CajaMedioPago::class => ['module' => 'ficheros', 'entity' => 'caja_medio_pago'],
        \App\Modules\admision\models\CajaBancoTarjeta::class => ['module' => 'ficheros', 'entity' => 'caja_banco_tarjeta'],
        \App\Modules\admision\models\TipoEmergencia::class => ['module' => 'ficheros', 'entity' => 'tipo_emergencia'],
        \App\Modules\admision\models\Topico::class => ['module' => 'ficheros', 'entity' => 'topico'],
        \App\Modules\admision\models\TipoDocumento::class => ['module' => 'ficheros', 'entity' => 'tipo_documento'],
        \App\Modules\admision\models\DocumentoAtencion::class => ['module' => 'ficheros', 'entity' => 'documento_atencion'],
        \App\Modules\admision\models\TarifaCategoria::class => ['module' => 'facturacion', 'entity' => 'tarifa_categoria'],
        \App\Modules\admision\models\TarifaSubcategoria::class => ['module' => 'facturacion', 'entity' => 'tarifa_subcategoria'],
        \App\Modules\admision\models\Paciente::class => ['module' => 'admision', 'entity' => 'paciente'],
        \App\Modules\admision\models\PacientePlan::class => ['module' => 'admision', 'entity' => 'paciente_plan'],
        \App\Modules\admision\models\PacienteContactoEmergencia::class => ['module' => 'admision', 'entity' => 'paciente_contacto_emergencia'],
        \App\Modules\admision\models\CitaAtencion::class => ['module' => 'admision', 'entity' => 'cita_atencion'],
        \App\Modules\admision\models\CitaAtencionServicio::class => ['module' => 'admision', 'entity' => 'cita_atencion_servicio'],
        \App\Modules\admision\models\PreFacturacionHospitalariaRegistro::class => ['module' => 'admision', 'entity' => 'prefacturacion_hospitalaria'],
        \App\Modules\admision\models\CuentaBitacoraNota::class => ['module' => 'admision', 'entity' => 'cuenta_bitacora_nota'],
        \App\Modules\admision\models\Cuenta::class => ['module' => 'admision', 'entity' => 'cuenta'],
        \App\Modules\caja\models\CajaApertura::class => ['module' => 'caja', 'entity' => 'caja_apertura'],
        \App\Modules\caja\models\CajaEmisionComprobante::class => ['module' => 'caja', 'entity' => 'emision_comprobante'],
        \App\Modules\caja\models\CajaEmisionComprobantePago::class => ['module' => 'caja', 'entity' => 'emision_comprobante'],
    ],
];
